import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { Providers, ThemeProviders } from '@/redux';
import './globals.css'
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<Providers>
			<html lang='en'>
				<body>
					<AppRouterCacheProvider>
						<ThemeProviders>{children}</ThemeProviders>
					</AppRouterCacheProvider>
				</body>
			</html>
		</Providers>
	);
}
